"""Enum constants matching the API swagger definitions."""

from enum import Enum


class ModelId(str, Enum):
    """Supported model identifiers."""

    UNSPECIFIED = "MODEL_ID_UNSPECIFIED"
    WHISPER_LARGE_V3 = "MODEL_ID_WHISPER_LARGE_V3"
    WHISPER_TURBO = "MODEL_ID_WHISPER_TURBO"
    GPT_OSS_20B = "MODEL_ID_GPT_OSS_20B"
    GPT_OSS_120B = "MODEL_ID_GPT_OSS_120B"
    OCR_DEEPSEEK = "MODEL_ID_OCR_DEEPSEEK"
    OCR_PADDLE = "MODEL_ID_OCR_PADDLE"
    OCR_PADDLE_VL = "MODEL_ID_OCR_PADDLE_VL"
    HIGGS_AUDIO_V2 = "MODEL_ID_HIGGS_AUDIO_V2"
    XTTS_V2 = "MODEL_ID_XTTS_V2"
    QWEN3_TTS = "MODEL_ID_QWEN3_TTS"
    QWEN3_TTS_FAST = "MODEL_ID_QWEN3_TTS_FAST"
    LLAMA_3_2_VISION_11B = "MODEL_ID_LLAMA_3_2_VISION_11B"
    LLAMA_3_2_VISION_90B = "MODEL_ID_LLAMA_3_2_VISION_90B"
    GLM_4_7_FLASH = "MODEL_ID_GLM_4_7_FLASH"
    WHISPERLIVE_TINY = "MODEL_ID_WHISPERLIVE_TINY"
    WHISPERLIVE_BASE = "MODEL_ID_WHISPERLIVE_BASE"
    WHISPERLIVE_SMALL = "MODEL_ID_WHISPERLIVE_SMALL"
    WHISPERLIVE_MEDIUM = "MODEL_ID_WHISPERLIVE_MEDIUM"
    WHISPERLIVE_LARGE_V3 = "MODEL_ID_WHISPERLIVE_LARGE_V3"
    WHISPERLIVE_TURBO = "MODEL_ID_WHISPERLIVE_TURBO"
    BREEZE_ASR_25 = "MODEL_ID_BREEZE_ASR_25"
    LLAMA_3_2_1B_GGUF = "MODEL_ID_LLAMA_3_2_1B_GGUF"
    LLAMA_3_2_3B_GGUF = "MODEL_ID_LLAMA_3_2_3B_GGUF"
    WHISPER_LARGE_V3_GGML = "MODEL_ID_WHISPER_LARGE_V3_GGML"
    WHISPER_SMALL_GGML = "MODEL_ID_WHISPER_SMALL_GGML"
    WHISPER_LARGE_V3_TURBO_GGML = "MODEL_ID_WHISPER_LARGE_V3_TURBO_GGML"
    QWEN_2_5_3B_GGUF = "MODEL_ID_QWEN_2_5_3B_GGUF"
    GEMMA_3_1B_GGUF = "MODEL_ID_GEMMA_3_1B_GGUF"
    QWEN_3_5_4B_GGUF = "MODEL_ID_QWEN_3_5_4B_GGUF"
    QWEN_3_5_9B = "MODEL_ID_QWEN_3_5_9B"
    QWEN_3_5_35B_A3B = "MODEL_ID_QWEN_3_5_35B_A3B"
    QWEN_3_5_122B_A10B = "MODEL_ID_QWEN_3_5_122B_A10B"
    QWEN_3_5_397B_A17B = "MODEL_ID_QWEN_3_5_397B_A17B"
    FISH_SPEECH_S2 = "MODEL_ID_FISH_SPEECH_S2"
    CHATTERBOX_MULTILINGUAL = "MODEL_ID_CHATTERBOX_MULTILINGUAL"


class ModelFamily(str, Enum):
    """Model family/category."""

    UNSPECIFIED = "MODEL_FAMILY_UNSPECIFIED"
    GPT = "MODEL_FAMILY_GPT"
    ASR = "MODEL_FAMILY_ASR"
    OCR = "MODEL_FAMILY_OCR"
    TTS = "MODEL_FAMILY_TTS"
    VISIONLLM = "MODEL_FAMILY_VISIONLLM"
    GLM = "MODEL_FAMILY_GLM"
    WHISPER_LIVE = "MODEL_FAMILY_WHISPER_LIVE"


class ModelFormat(str, Enum):
    """Input/output data format of a model."""

    UNSPECIFIED = "MODEL_FORMAT_UNSPECIFIED"
    TEXT = "MODEL_FORMAT_TEXT"
    AUDIO = "MODEL_FORMAT_AUDIO"
    IMAGE = "MODEL_FORMAT_IMAGE"
    VIDEO = "MODEL_FORMAT_VIDEO"


class ModelStatusEnum(str, Enum):
    """Model runtime status."""

    UNSPECIFIED = "MODEL_STATUS_UNSPECIFIED"
    COLD = "MODEL_STATUS_COLD"
    STARTING = "MODEL_STATUS_STARTING"
    HEALTHY = "MODEL_STATUS_HEALTHY"
    UNHEALTHY = "MODEL_STATUS_UNHEALTHY"
    STOPPED = "MODEL_STATUS_STOPPED"


class JobStatus(str, Enum):
    """Async job status."""

    UNSPECIFIED = "JOB_STATUS_UNSPECIFIED"
    PENDING = "JOB_STATUS_PENDING"
    PROCESSING = "JOB_STATUS_PROCESSING"
    COMPLETED = "JOB_STATUS_COMPLETED"
    FAILED = "JOB_STATUS_FAILED"


class ColdStartStage(str, Enum):
    """Cold start progress stage."""

    UNSPECIFIED = "COLD_START_STAGE_UNSPECIFIED"
    QUEUED = "COLD_START_STAGE_QUEUED"
    SPAWNING = "COLD_START_STAGE_SPAWNING"
    LOADING = "COLD_START_STAGE_LOADING"
    WARMING = "COLD_START_STAGE_WARMING"
    READY = "COLD_START_STAGE_READY"


class RequestPhase(str, Enum):
    """Request processing phase."""

    UNSPECIFIED = "REQUEST_PHASE_UNSPECIFIED"
    WARMUP = "REQUEST_PHASE_WARMUP"
    UPLOADING = "REQUEST_PHASE_UPLOADING"
    PROCESSING = "REQUEST_PHASE_PROCESSING"
    COMPLETE = "REQUEST_PHASE_COMPLETE"


class PlanTier(str, Enum):
    """Subscription plan tier."""

    UNSPECIFIED = "PLAN_TIER_UNSPECIFIED"
    FREE = "PLAN_TIER_FREE"
    STARTER = "PLAN_TIER_STARTER"
    PRO = "PLAN_TIER_PRO"
    ENTERPRISE = "PLAN_TIER_ENTERPRISE"


class OCRMode(str, Enum):
    """OCR processing mode."""

    UNSPECIFIED = "OCR_MODE_UNSPECIFIED"
    MARKDOWN = "OCR_MODE_MARKDOWN"
    GENERIC = "OCR_MODE_GENERIC"
    FIGURE = "OCR_MODE_FIGURE"
    GROUNDING = "OCR_MODE_GROUNDING"


class OCRResolution(str, Enum):
    """OCR image processing resolution."""

    UNSPECIFIED = "OCR_RESOLUTION_UNSPECIFIED"
    AUTO = "OCR_RESOLUTION_AUTO"
    TINY = "OCR_RESOLUTION_TINY"
    SMALL = "OCR_RESOLUTION_SMALL"
    BASE = "OCR_RESOLUTION_BASE"
    LARGE = "OCR_RESOLUTION_LARGE"


class TTSLanguage(str, Enum):
    """TTS language codes."""

    UNSPECIFIED = "TTS_LANGUAGE_UNSPECIFIED"
    EN = "TTS_LANGUAGE_EN"
    ZH = "TTS_LANGUAGE_ZH"
    JA = "TTS_LANGUAGE_JA"
    KO = "TTS_LANGUAGE_KO"
    DE = "TTS_LANGUAGE_DE"
    FR = "TTS_LANGUAGE_FR"
    RU = "TTS_LANGUAGE_RU"
    PT = "TTS_LANGUAGE_PT"
    ES = "TTS_LANGUAGE_ES"
    IT = "TTS_LANGUAGE_IT"
    ID = "TTS_LANGUAGE_ID"
    MS = "TTS_LANGUAGE_MS"


class VisionAnalysisMode(str, Enum):
    """Vision analysis mode preset."""

    UNSPECIFIED = "VISION_ANALYSIS_MODE_UNSPECIFIED"
    GENERAL = "VISION_ANALYSIS_MODE_GENERAL"
    DOCUMENT = "VISION_ANALYSIS_MODE_DOCUMENT"
    CHART = "VISION_ANALYSIS_MODE_CHART"
    CODE = "VISION_ANALYSIS_MODE_CODE"
    DETAILED = "VISION_ANALYSIS_MODE_DETAILED"
